nodeLinker: node-modules

npmRegistryServer: "http://localhost:4873"

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.5.1.cjs
